# Generated by Django 4.0.4 on 2022-05-16 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_remove_user_address_remove_user_birthday_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='product',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
