# Generated by Django 4.0.4 on 2022-05-23 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0026_product_shop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='id_product',
        ),
    ]
