# Generated by Django 4.0.4 on 2022-05-23 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0027_remove_product_id_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='product',
        ),
        migrations.AddField(
            model_name='shop',
            name='product',
            field=models.ManyToManyField(to='authentication.product'),
        ),
    ]
