# Generated by Django 4.0.4 on 2022-05-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0028_remove_shop_product_shop_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='shop',
            field=models.ManyToManyField(to='authentication.shop'),
        ),
    ]
