# Generated by Django 4.0.4 on 2022-05-25 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0031_product_shop_alter_track_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='product',
            new_name='products',
        ),
    ]
