# Generated by Django 4.0.4 on 2022-05-25 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0032_rename_product_shop_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='address_shop',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
