# Generated by Django 4.0.4 on 2022-05-25 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0033_alter_shop_address_shop'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='address_shop',
            new_name='addressShop',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name_product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_product',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='email_shop',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='name_shop',
        ),
        migrations.AddField(
            model_name='product',
            name='nameProduct',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='priceProduct',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='emailShop',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='nameShop',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
