# Generated by Django 4.0.4 on 2022-05-25 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0034_rename_address_shop_shop_addressshop_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='addressShop',
            new_name='address_shop',
        ),
        migrations.RemoveField(
            model_name='product',
            name='nameProduct',
        ),
        migrations.RemoveField(
            model_name='product',
            name='priceProduct',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='emailShop',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='nameShop',
        ),
        migrations.AddField(
            model_name='product',
            name='name_product',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price_product',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='email_shop',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='name_shop',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
