# Generated by Django 4.0.4 on 2022-05-25 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0035_rename_addressshop_shop_address_shop_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='name_product',
        ),
    ]
