# Generated by Django 4.0.4 on 2022-05-25 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0036_remove_product_name_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name_product',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
