# Generated by Django 4.0.4 on 2022-05-27 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0037_product_name_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='membre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
