# Generated by Django 4.0.4 on 2022-05-27 11:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0038_user_membre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='membre',
        ),
        migrations.AddField(
            model_name='user',
            name='membre',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
