# Generated by Django 4.0.4 on 2022-05-27 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0041_alter_user_membre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bracelet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=4)),
                ('maximum_amount', models.DecimalField(decimal_places=3, max_digits=4)),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authentication.shop')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
