# Generated by Django 4.0.4 on 2022-06-20 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0042_bracelet'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_product',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='image_shop',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
