# Generated by Django 4.0.4 on 2022-06-27 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0044_alter_product_image_product_alter_shop_image_shop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_membre',
            field=models.BooleanField(default=False),
        ),
    ]
