# Generated by Django 4.0.4 on 2022-07-05 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0045_user_is_admin_user_is_membre'),
    ]

    operations = [
        migrations.CreateModel(
            name='card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=100)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=100)),
                ('currency', models.CharField(default='DT', max_length=50)),
                ('account_number', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterModelOptions(
            name='bracelet',
            options={'ordering': ('-creation_date',), 'verbose_name': 'cart', 'verbose_name_plural': 'carts'},
        ),
        migrations.AddField(
            model_name='bracelet',
            name='creation_date',
            field=models.DateTimeField(null=True, verbose_name='creation date'),
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('receive', 'receive'), ('transfer', 'transfer'), ('payment', 'payment')], max_length=200, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=100, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('status', models.CharField(default='pending', max_length=100)),
                ('paystack_payment_reference', models.CharField(blank=True, default='', max_length=100)),
                ('wallet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.wallet')),
            ],
        ),
    ]
