# Generated by Django 4.0.4 on 2022-07-05 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0049_alter_wallet_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='amount',
            field=models.DecimalField(decimal_places=3, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(decimal_places=3, max_digits=4),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='amount',
            field=models.DecimalField(decimal_places=3, max_digits=4, null=True),
        ),
    ]
